#!/usr/bin/python
from http_analyzer import http_analyzer
from login import search_brute_force
from alert import searcher
from pdfdocument.document import PDFDocument
from dns_analyzer import search_dns
from malicious_file_scanner import scan_files
from corelation import corelation

c = PDFDocument("THREAT_HUNT_REPORT_DON.pdf")
c.init_report()
c.h1("		THREAT-HUNT-REPORT	\n\n")
c.p("autogenerated by python\n\nauthor: Nishan Maharjan\n\n")
http_analyzer(c)
search_brute_force(c)
search_dns(c)
scan_files(c)
corelation(c)
L = []
searcher(L,c)
c.generate()
